image: ruby:2.4.2
stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  variables:
    DATABASE_URL: 'mongodb://mongo/user_posts'
  before_script:
   - cd reddit
   - bundle install
  script:
    - echo 'Building'

test_unit_job:
  stage: test
  script:
    - echo 'Testing 1'

test_integration_job:
  stage: test
  services:
    - mongo:latest
  before_script:
    - gem install sinatra
    - gem install haml
    - gem install mongo
    - gem install bcrypt rack-test json puma
  script:
    - ruby reddit/simpletest.rb 
    - echo 'Testing 2'

deploy_job:
  stage: deploy
  script:
    - echo 'Deploy'