image: ruby:2.4.2
stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  variables:
    DATABASE_URL: 'mongodb://mongo/user_posts'
  before_script:
   - cd reddit
   - bundle install
  script:
    - echo 'Building'

test_unit_job:
  stage: test
  script:
    - echo 'Testing 1'

test_integration_job:
  stage: test
  services:
    - mongo:latest
  before_script:
    - bundle install
    - export SERVER_IP=127.0.0.1
    - export REPO_NAME=root/reddit
    - export DEPLOY_USER=appuser
    - bundle exec cap production deploy:initial
  script:
    - ruby reddit/simpletest.rb 
    - echo 'Testing 2'

deploy_job:
  stage: deploy
  script:
    - echo 'Deploy'