distr: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-11/run.sh | 
  bash
# script:
#   - wget https://releases.hashicorp.com/terraform/0.11.11/terraform_0.11.11_linux_amd64.zip -O /tmp/terraform.zip
#   - sudo unzip -o -d  /usr/local/bin/ /tmp/terraform.zip
#   - wget https://releases.hashicorp.com/packer/1.3.4/packer_1.3.4_linux_amd64.zip -O /tmp/packer.zip
#   - sudo unzip -o -d  /usr/local/bin/ /tmp/packer.zip
#   - wget https://github.com/wata727/tflint/releases/download/v0.7.3/tflint_linux_amd64.zip -O /tmp/tflint.zip
#   - sudo unzip -o -d  /usr/local/bin/ /tmp/tflint.zip
#   - pip install ansible-lint --user
#   - ansible-lint ansible/playbooks/site.yml
#   - ansible-lint ansible/playbooks/site_dynamic.yml
#   - packer validate -var-file=packer/variables.json.example packer/app.json
#   - packer validate -var-file=packer/variables.json.example packer/db.json
#   - cd packer
#   - packer validate -var-file=variables.json.example immutable.json
#   - packer validate -var-file=variables.json.example ubuntu16.json
#   - ssh-keygen -f ~/.ssh/appuser -q -N ""
#   - cd ../terraform/prod
#   - cp terraform.tfvars.example terraform.tfvars
#   - terraform get
#   - terraform init
#   - terraform validate
#   - tflint
#   - cd ../stage/
#   - cp terraform.tfvars.example terraform.tfvars
#   - terraform get
#   - terraform init
#   - terraform validate
#   - tflint
notifications:
  slack:
    rooms:
      secure: HWxFBmOu+5LXL/xDfECrAXkTLH2cgr/ZtmrDXkIwyoA9wBiu23uVjZtrMgpION6llKkGaHUekGrNpNMvPfgrnDiaeJpPmlyZVg3TNCMx1UfY/Gyh5Pody32vVdM+vMxChFKmsJ1AVuNF4VQ9FWje7pln+s7iGCatkoPKFbFOVdWII6uYUf8D7kFGIoDCVbNliHbl3MYHA18Pi/auYi+9iegeybVIkSdhNEFc4lrzOVbcXREsXDvx58WWKPjAkgdAr6X0RjeccvfHCcJhmQXnxZO3WXvgYipwe01J8lTF9oIutynHFpzedYeds4RwpWpFYeTT0w/TdBp23duzrZ7Vnu466g/zshcNliH6NK0Ue3WGOlapsar4aBZRECFPNzO3/+UgGePwiAC7k9rfQpjIoWelveKQrPMDKV8iNbfC1mZ2+6H9422HyylmoFfIPTfjO2jv1u5SJBwz4k+l/T7/SW3z+8ZQPZApyIfYVaY0FyiHsjdveCNw4Vun2pmlmQRlMHUrka2CmqLCqlpVghP3d+5nPYUjtfb6Off5i1MoxoVWBKkb1pbawGJqyVjGm8qZl0mDAEjf2PMfXCqCESn8gw5Zdz9eH2dawT7vh32SqbebEIAJiyLfobnRC0r3Yqa5LWfklYmHpMpw2C/cNSgWN19Xx/ljonKxk+9TvMdu0uo=
