version: '3'
services:
  fluentd:
    image: dmitriyboon/fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    image: elasticsearch:6.5.0
    expose:
      - 9200
    ports:
      - "9200:9200"

  kibana:
    image: kibana:6.7.0
    ports:
      - "5601:5601"
 

