version: '3'
services:
  fluentd:
    image: ${USERNAME}/fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - front_net
      - back_net

  elasticsearch:
    image: elasticsearch:5-alpine
    expose:
      - 9200
    ports:
      - "9200:9200"
    networks:
      - back_net
      - front_net

  kibana:
    image: kibana:5
    ports:
      - "5601:5601"
    networks:
      - front_net
      - back_net

networks:
  front_net:
  back_net:
